-- Quartz SQL Server 建表脚本（前缀 microi_job_）
-- 在 microi 数据库中执行此脚本

IF OBJECT_ID(N'[dbo].[microi_job_CALENDARS]', N'U') IS NULL
CREATE TABLE [dbo].[microi_job_CALENDARS] (
    [SCHED_NAME]    NVARCHAR(120) NOT NULL,
    [CALENDAR_NAME] NVARCHAR(200) NOT NULL,
    [CALENDAR]      VARBINARY(MAX) NOT NULL,
    CONSTRAINT [PK_microi_job_CALENDARS] PRIMARY KEY CLUSTERED ([SCHED_NAME],[CALENDAR_NAME])
);

IF OBJECT_ID(N'[dbo].[microi_job_CRON_TRIGGERS]', N'U') IS NULL
CREATE TABLE [dbo].[microi_job_CRON_TRIGGERS] (
    [SCHED_NAME]      NVARCHAR(120) NOT NULL,
    [TRIGGER_NAME]    NVARCHAR(200) NOT NULL,
    [TRIGGER_GROUP]   NVARCHAR(200) NOT NULL,
    [CRON_EXPRESSION] NVARCHAR(120) NOT NULL,
    [TIME_ZONE_ID]    NVARCHAR(80),
    CONSTRAINT [PK_microi_job_CRON_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME],[TRIGGER_NAME],[TRIGGER_GROUP]),
    CONSTRAINT [FK_microi_job_CRON_TRIGGERS_TRIGGERS] FOREIGN KEY ([SCHED_NAME],[TRIGGER_NAME],[TRIGGER_GROUP]) 
        REFERENCES [dbo].[microi_job_TRIGGERS]([SCHED_NAME],[TRIGGER_NAME],[TRIGGER_GROUP]) ON DELETE CASCADE
);

IF OBJECT_ID(N'[dbo].[microi_job_FIRED_TRIGGERS]', N'U') IS NULL
CREATE TABLE [dbo].[microi_job_FIRED_TRIGGERS] (
    [SCHED_NAME]        NVARCHAR(120) NOT NULL,
    [ENTRY_ID]          NVARCHAR(95)  NOT NULL,
    [TRIGGER_NAME]      NVARCHAR(200) NOT NULL,
    [TRIGGER_GROUP]     NVARCHAR(200) NOT NULL,
    [INSTANCE_NAME]     NVARCHAR(200) NOT NULL,
    [FIRED_TIME]        BIGINT        NOT NULL,
    [SCHED_TIME]        BIGINT        NOT NULL,
    [PRIORITY]          INT           NOT NULL,
    [STATE]             NVARCHAR(16)  NOT NULL,
    [JOB_NAME]          NVARCHAR(200) NULL,
    [JOB_GROUP]         NVARCHAR(200) NULL,
    [IS_NONCONCURRENT]  BIT           NULL,
    [REQUESTS_RECOVERY] BIT           NULL,
    CONSTRAINT [PK_microi_job_FIRED_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME],[ENTRY_ID])
);

IF OBJECT_ID(N'[dbo].[microi_job_JOB_DETAILS]', N'U') IS NULL
CREATE TABLE [dbo].[microi_job_JOB_DETAILS] (
    [SCHED_NAME]        NVARCHAR(120) NOT NULL,
    [JOB_NAME]          NVARCHAR(200) NOT NULL,
    [JOB_GROUP]         NVARCHAR(200) NOT NULL,
    [DESCRIPTION]       NVARCHAR(250) NULL,
    [JOB_CLASS_NAME]    NVARCHAR(250) NOT NULL,
    [IS_DURABLE]        BIT           NOT NULL,
    [IS_NONCONCURRENT]  BIT           NOT NULL,
    [IS_UPDATE_DATA]    BIT           NOT NULL,
    [REQUESTS_RECOVERY] BIT           NOT NULL,
    [JOB_DATA]          VARBINARY(MAX) NULL,
    CONSTRAINT [PK_microi_job_JOB_DETAILS] PRIMARY KEY CLUSTERED ([SCHED_NAME],[JOB_NAME],[JOB_GROUP])
);

IF OBJECT_ID(N'[dbo].[microi_job_LOCKS]', N'U') IS NULL
CREATE TABLE [dbo].[microi_job_LOCKS] (
    [SCHED_NAME] NVARCHAR(120) NOT NULL,
    [LOCK_NAME]  NVARCHAR(40)  NOT NULL,
    CONSTRAINT [PK_microi_job_LOCKS] PRIMARY KEY CLUSTERED ([SCHED_NAME],[LOCK_NAME])
);

IF OBJECT_ID(N'[dbo].[microi_job_PAUSED_TRIGGER_GRPS]', N'U') IS NULL
CREATE TABLE [dbo].[microi_job_PAUSED_TRIGGER_GRPS] (
    [SCHED_NAME]    NVARCHAR(120) NOT NULL,
    [TRIGGER_GROUP] NVARCHAR(200) NOT NULL,
    CONSTRAINT [PK_microi_job_PAUSED_TRIGGER_GRPS] PRIMARY KEY CLUSTERED ([SCHED_NAME],[TRIGGER_GROUP])
);

IF OBJECT_ID(N'[dbo].[microi_job_SCHEDULER_STATE]', N'U') IS NULL
CREATE TABLE [dbo].[microi_job_SCHEDULER_STATE] (
    [SCHED_NAME]        NVARCHAR(120) NOT NULL,
    [INSTANCE_NAME]     NVARCHAR(200) NOT NULL,
    [LAST_CHECKIN_TIME] BIGINT        NOT NULL,
    [CHECKIN_INTERVAL]  BIGINT        NOT NULL,
    CONSTRAINT [PK_microi_job_SCHEDULER_STATE] PRIMARY KEY CLUSTERED ([SCHED_NAME],[INSTANCE_NAME])
);

IF OBJECT_ID(N'[dbo].[microi_job_SIMPLE_TRIGGERS]', N'U') IS NULL
CREATE TABLE [dbo].[microi_job_SIMPLE_TRIGGERS] (
    [SCHED_NAME]      NVARCHAR(120) NOT NULL,
    [TRIGGER_NAME]    NVARCHAR(200) NOT NULL,
    [TRIGGER_GROUP]   NVARCHAR(200) NOT NULL,
    [REPEAT_COUNT]    BIGINT        NOT NULL,
    [REPEAT_INTERVAL] BIGINT        NOT NULL,
    [TIMES_TRIGGERED] BIGINT        NOT NULL,
    CONSTRAINT [PK_microi_job_SIMPLE_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME],[TRIGGER_NAME],[TRIGGER_GROUP]),
    CONSTRAINT [FK_microi_job_SIMPLE_TRIGGERS_TRIGGERS] FOREIGN KEY ([SCHED_NAME],[TRIGGER_NAME],[TRIGGER_GROUP]) 
        REFERENCES [dbo].[microi_job_TRIGGERS]([SCHED_NAME],[TRIGGER_NAME],[TRIGGER_GROUP]) ON DELETE CASCADE
);

IF OBJECT_ID(N'[dbo].[microi_job_SIMPROP_TRIGGERS]', N'U') IS NULL
CREATE TABLE [dbo].[microi_job_SIMPROP_TRIGGERS] (
    [SCHED_NAME]    NVARCHAR(120) NOT NULL,
    [TRIGGER_NAME]  NVARCHAR(200) NOT NULL,
    [TRIGGER_GROUP] NVARCHAR(200) NOT NULL,
    [STR_PROP_1]    NVARCHAR(512) NULL,
    [STR_PROP_2]    NVARCHAR(512) NULL,
    [STR_PROP_3]    NVARCHAR(512) NULL,
    [INT_PROP_1]    INT           NULL,
    [INT_PROP_2]    INT           NULL,
    [LONG_PROP_1]   BIGINT        NULL,
    [LONG_PROP_2]   BIGINT        NULL,
    [DEC_PROP_1]    DECIMAL(13,4) NULL,
    [DEC_PROP_2]    DECIMAL(13,4) NULL,
    [BOOL_PROP_1]   BIT           NULL,
    [BOOL_PROP_2]   BIT           NULL,
    CONSTRAINT [PK_microi_job_SIMPROP_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME],[TRIGGER_NAME],[TRIGGER_GROUP]),
    CONSTRAINT [FK_microi_job_SIMPROP_TRIGGERS_TRIGGERS] FOREIGN KEY ([SCHED_NAME],[TRIGGER_NAME],[TRIGGER_GROUP]) 
        REFERENCES [dbo].[microi_job_TRIGGERS]([SCHED_NAME],[TRIGGER_NAME],[TRIGGER_GROUP]) ON DELETE CASCADE
);

IF OBJECT_ID(N'[dbo].[microi_job_BLOB_TRIGGERS]', N'U') IS NULL
CREATE TABLE [dbo].[microi_job_BLOB_TRIGGERS] (
    [SCHED_NAME]    NVARCHAR(120) NOT NULL,
    [TRIGGER_NAME]  NVARCHAR(200) NOT NULL,
    [TRIGGER_GROUP] NVARCHAR(200) NOT NULL,
    [BLOB_DATA]     VARBINARY(MAX) NULL,
    CONSTRAINT [PK_microi_job_BLOB_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME],[TRIGGER_NAME],[TRIGGER_GROUP]),
    CONSTRAINT [FK_microi_job_BLOB_TRIGGERS_TRIGGERS] FOREIGN KEY ([SCHED_NAME],[TRIGGER_NAME],[TRIGGER_GROUP]) 
        REFERENCES [dbo].[microi_job_TRIGGERS]([SCHED_NAME],[TRIGGER_NAME],[TRIGGER_GROUP]) ON DELETE CASCADE
);

IF OBJECT_ID(N'[dbo].[microi_job_TRIGGERS]', N'U') IS NULL
CREATE TABLE [dbo].[microi_job_TRIGGERS] (
    [SCHED_NAME]     NVARCHAR(120) NOT NULL,
    [TRIGGER_NAME]   NVARCHAR(200) NOT NULL,
    [TRIGGER_GROUP]  NVARCHAR(200) NOT NULL,
    [JOB_NAME]       NVARCHAR(200) NOT NULL,
    [JOB_GROUP]      NVARCHAR(200) NOT NULL,
    [DESCRIPTION]    NVARCHAR(250) NULL,
    [NEXT_FIRE_TIME] BIGINT        NULL,
    [PREV_FIRE_TIME] BIGINT        NULL,
    [PRIORITY]       INT           NULL,
    [TRIGGER_STATE]  NVARCHAR(16)  NOT NULL,
    [TRIGGER_TYPE]   NVARCHAR(8)   NOT NULL,
    [START_TIME]     BIGINT        NOT NULL,
    [END_TIME]       BIGINT        NULL,
    [CALENDAR_NAME]  NVARCHAR(200) NULL,
    [MISFIRE_INSTR]  INT           NULL,
    [JOB_DATA]       VARBINARY(MAX) NULL,
    CONSTRAINT [PK_microi_job_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME],[TRIGGER_NAME],[TRIGGER_GROUP]),
    CONSTRAINT [FK_microi_job_TRIGGERS_JOB_DETAILS] FOREIGN KEY ([SCHED_NAME],[JOB_NAME],[JOB_GROUP]) 
        REFERENCES [dbo].[microi_job_JOB_DETAILS]([SCHED_NAME],[JOB_NAME],[JOB_GROUP])
);

CREATE NONCLUSTERED INDEX [IDX_microi_job_TRIGGERS_NEXT_FIRE_TIME] ON [dbo].[microi_job_TRIGGERS] ([SCHED_NAME], [NEXT_FIRE_TIME]);
CREATE NONCLUSTERED INDEX [IDX_microi_job_TRIGGERS_STATE] ON [dbo].[microi_job_TRIGGERS] ([SCHED_NAME], [TRIGGER_STATE]);

PRINT 'Quartz tables (microi_job_*) created successfully.';
